### ISSUE TITLE
Emoji 15.1 is not supported

### ISSUE THREAD

**Issue by frebib** [sigpwned/emoji4j#126]
None of these are recognised as graphemes
https://emojipedia.org/emoji-15.1

**Comment by sigpwned** [comment]
I released v15.1.0 and have confirmed that all emoji in Unicode 15.1 are supported. Please feel free to re-open this issue, or to open a new one, if you find any issues in the new version!

**Comment by frebib** [comment]
Thanks very much. This works great!
